export const elements = {
  main: document.querySelector('#main'),
  container: document.querySelector('#container'),
  hashtag_container: document.querySelector('#hashtag_container'),
  search: document.querySelector('#form-submit'),
  searchInput: document.querySelector('.search-input'),
  searchButton: document.querySelector('.search__btn'),
  avatar: document.querySelector('.user_avatar'),
  first_hashtag: document.querySelector('#first_hashtag'),
  first_image: document.querySelector('#first_image'),
  tips_description: document.querySelector('.tips_description'),
  sectionHashtag: document.querySelector('#hashtags'),
  sectionMedia: document.querySelector('#media'),

  mondayD: document.querySelector('#days .monday'),
  tuesdayD: document.querySelector('#days .tuesday'),
  wednesdayD: document.querySelector('#days .wednesday'),
  thursdayD: document.querySelector('#days .thursday'),
  fridayD: document.querySelector('#days .friday'),
  saturdayD: document.querySelector('#days .saturday'),
  sundayD: document.querySelector('#days .sunday'),

  mondayH: document.querySelector('#hours .monday'),
  tuesdayH: document.querySelector('#hours .tuesday'),
  wednesdayH: document.querySelector('#hours .wednesday'),
  thursdayH: document.querySelector('#hours .thursday'),
  fridayH: document.querySelector('#hours .friday'),
  saturdayH: document.querySelector('#hours .saturday'),
  sundayH: document.querySelector('#hours .sunday'),

  monday_day: document.querySelector('.monday .best_day'),
  tuesday_day: document.querySelector('.tuesday .best_day'),
  wednesday_day: document.querySelector('.wednesday .best_day'),
  thursday_day: document.querySelector('.thursday .best_day'),
  friday_day: document.querySelector('.friday .best_day'),
  saturday_day: document.querySelector('.saturday .best_day'),
  sunday_day: document.querySelector('.sunday .best_day'),

  monday_time: document.querySelector('.monday_time'),
  tuesday_time: document.querySelector('.tuesday_time'),
  wednesday_time: document.querySelector('.wednesday_time'),
  thursday_time: document.querySelector('.thursday_time'),
  friday_time: document.querySelector('.friday_time'),
  saturday_time: document.querySelector('.saturday_time'),
  sunday_time: document.querySelector('.sunday_time'),

  monday_best_time: document.querySelector('.monday_best_time'),
  tuesday_best_time: document.querySelector('.tuesday_best_time'),
  wednesday_best_time: document.querySelector('.wednesday_best_time'),
  thursday_best_time: document.querySelector('.thursday_best_time'),
  friday_best_time: document.querySelector('.friday_best_time'),
  saturday_best_time: document.querySelector('.saturday_best_time'),
  sunday_best_time: document.querySelector('.sunday_best_time')

}
